### ISSUE TITLE
Make twuckoo more robust

### ISSUE THREAD

**Issue by balinterdi** [balinterdi/twuckoo#12]
Currently twuckoo instances die every few days. I suspect it might be because receiving an error from Twitter (overload -> timeout) and there is no exception handling.

**Comment by balinterdi** [comment]
Here is an error stack trace I saw:

```
/usr/local/lib/ruby/gems/1.9.1/gems/twuckoo-0.5.1/lib/twuckoo/runner.rb:155:in `block in send_email': undefined method `smtp' for #<Mail::Configuration:0x93c0ab0> (NoMethodError)
    from /usr/local/lib/ruby/gems/1.9.1/gems/mail-2.2.15/lib/mail/mail.rb:106:in `instance_eval'
    from /usr/local/lib/ruby/gems/1.9.1/gems/mail-2.2.15/lib/mail/mail.rb:106:in `defaults'
    from /usr/local/lib/ruby/gems/1.9.1/gems/twuckoo-0.5.1/lib/twuckoo/runner.rb:154:in `send_email'
    from /usr/local/lib/ruby/gems/1.9.1/gems/twuckoo-0.5.1/lib/twuckoo/runner.rb:79:in `notify'
    from /usr/local/lib/ruby/gems/1.9.1/gems/twuckoo-0.5.1/lib/twuckoo/runner.rb:23:in `run'
    from /usr/local/lib/ruby/gems/1.9.1/gems/twuckoo-0.5.1/bin/twuckoo:8:in `<top (required)>'
    from /usr/local/bin/twuckoo:19:in `load'
    from /usr/local/bin/twuckoo:19:in `<main>'
```
